

# server port configuration
Server:
  port: 20221

# database connection configurations
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/capture?useSSL=false
    username: root
    password: password

# coloring logs for easy of reading
  output:
    ansi:
      enabled: always

# jpa configurations for the database
  jpa:
    hibernate:
      ddl-auto: create
      show-sql: true

# Secret key for the token generation
jwt:
  secretKey: HereIsMySTRONGSuperSECRETKEY001

